---

- block:

  - name: Docker APT repo key
    apt_key:
      state: present
      url: "{{ docker_repository_key }}"

  - name: Docker Repository (Debian)
    apt_repository:
      state: present
      repo: "{{ docker_repository_apt }}"
      update_cache: yes

  when: docker_repository_enabled

# Install from url
#- block:
#
#  when: not docker_repository_enabled

# vi:ts=2:sw=2:et:ft=yaml
