---

- name: Docker Yum Repository (RedHat)
  yum_repository:
    name: docker-ce
    description: docker-ce
    state: present
    baseurl:  "{{ docker_repository_yum }}"
    gpgkey:   "{{ docker_repository_key }}"
    gpgcheck: true

# vi:ts=2:sw=2:et:ft=yaml
