---

- include: install/Debian.yml
  when: ansible_os_family == 'Debian'

- include: install/RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Install Docker from repo
  package:
    name: "{{ docker_package }}"
    state: present
  when: docker_repository_enabled

- name: Docker Python Packages
  pip:
    name: "{{ docker_pip_packages }}"
    state: present
    executable: "{{ docker_pip_bin }}"
  when: docker_pip_packages_install

- name: Remove OpenSSL Python directory
  file:
    state: absent
    path: /usr/lib/python3/dist-packages/OpenSSL

- name: Reinstall pyopenssl
  pip:
    name: pyopenssl
    state: forcereinstall
    executable: "{{ docker_pip_bin }}"

- name: Amazon Credential Helper
  get_url:
    url: "{{ docker_aws_credential_helper_pkg }}"
    dest: "{{ docker_aws_credential_helper_bin_prefix }}/{{ docker_aws_credential_helper_bin }}"
    mode: 0755
    owner: root
    group: root
  when: docker_aws_credential_helper_install

# vi:ts=2:sw=2:et:ft=yaml
